version: '3'

services:
  db:
    container_name: thanks-bank-db
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: "thanks-bank"  #postgresのDatabase名
      POSTGRES_USER: "postgres_user"  #postgresのユーザー名
      POSTGRES_PASSWORD: "postgres_pass"  #postgresのパスワード
      PGDATA: /var/lib/postgresql/data  #保存場所
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres-data: